In [1]:
import numpy as np

In [2]:
mylist = np.zeros(10)
mylist

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:

mylist = np.arange(10,49)
mylist

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [4]:
mylist.shape

(39,)

In [5]:
mylist.dtype

dtype('int32')

In [6]:
print(f"Numpy Version : {np.__version__}")
print(np.show_config())

Numpy Version : 1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [7]:
mylist.ndim

1

In [8]:
myBoolList = np.ones(10,dtype=bool)
myBoolList

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [9]:
my2dList = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
my2dList

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [10]:
my3dList = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
my3dList

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
mylist = np.arange(10)
np.flipud(mylist)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
mylist = np.zeros(10)
mylist[4] = 1
mylist

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:

mylist = np.arange(1,10).reshape(3,3)
mylist

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr = np.array([1,2,3,4,5])
#changing data type
arr = arr.astype("float32")
#printing array
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
arr1 = np.array([   [1., 2., 3.],
                    [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])

arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr3 = arr1==arr2
arr3

array([[False, False, False],
       [False, False, False]])

In [17]:
arr = np.arange(0,9)
odd_in_arr=arr[arr % 2 != 0]
odd_in_arr

array([1, 3, 5, 7])

In [18]:
arr[odd_in_arr] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [19]:
arr = np.arange(10)
arr[5:9] = 12


In [20]:
arr = np.ones((10,10))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
arr2d = np.array([  [1, 2, 3],
                    [4, 5, 6], 
                    [7, 8, 9]
                 ])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0][:]=64
arr3d[0][1][:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d[0]

array([0, 1, 2])

In [24]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d[1:2,1:2]


array([[4]])

In [25]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d[0:2,2:]

array([[2],
       [5]])

In [26]:
arr = np.random.randint(1000, size=100).reshape(10,10)
arr

array([[130, 616, 344, 181, 687, 303, 948, 513, 869, 653],
       [154, 983, 833, 267,  12,  98, 149, 279, 360, 509],
       [559,  92, 758, 307, 660, 320, 892, 694, 710, 893],
       [131, 174,  55, 961, 597, 479, 652,  73, 295, 276],
       [816, 223, 666, 768, 187, 449, 805, 872,  15, 471],
       [270, 508, 550, 591, 506, 870, 879, 668, 161, 849],
       [  7,   7, 427, 661, 483, 122, 362, 360, 793, 950],
       [889, 452, 347, 701, 656, 329, 164,  54, 462, 694],
       [133, 958, 211, 878, 460, 946, 832, 730, 117, 520],
       [588, 209, 812, 518, 221, 437, 425, 434, 281, 373]])

In [27]:
np.amin(arr)

7

In [28]:
np.amax(arr)

983

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
common

array([2, 4])

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
position = np.intersect1d(a,b, return_indices=True)
position

(array([2, 4]), array([1, 5], dtype=int32), array([1, 5], dtype=int32))

In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')